import {QdrantClient} from "@qdrant/js-client-rest";
import dotenv from "dotenv";

dotenv.config();

const qdrantClient = new QdrantClient({
  url: process.env.QUADRANT_END_POINT,
  apiKey: process.env.QUADRANT_API_KEY,
});

const initFrameworkCollection = async () => {
  const collectionName = "frameworks";
  try {
    const res = await qdrantClient.getCollections();
    const exists = res.collections.some((c) => c.name === collectionName);

    if (!exists) {
      await qdrantClient.createCollection(collectionName, {
        vectors: {
          size: 384, // The vector size generated by our Hugging Face model
          distance: "Cosine", // Standard distance metric for text embeddings
        },
      });
      // Create a payload index so we can filter by frameworkId
      await qdrantClient.createPayloadIndex(collectionName, {
        field_name: "frameworkId",
        field_schema: "keyword",
      });
      console.log(
        `✅ Qdrant Collection '${collectionName}' created successfully.`,
      );
    } else {
      console.log(`ℹ️ Qdrant Collection '${collectionName}' already exists.`);
    }
  } catch (err) {
    console.error(
      `❌ Error setting up Qdrant Collection '${collectionName}':`,
      err,
    );
  }
};

const connectQdrant = async () => {
  try {
    const res = await qdrantClient.getCollections();

    console.log(`Qdrant Connected: ${res.collections.length} collections`);
    await initFrameworkCollection();
  } catch (error) {
    console.log("Qdrant Connection Failed:", error.message);
  }
};

export {qdrantClient, connectQdrant};
